In [ ]:
#Simple Linear Regression With scikit-learn

In [1]:
 import numpy as np
from sklearn.linear_model import LinearRegression

In [3]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([5, 20, 14, 32, 22, 38])

In [5]:
model = LinearRegression()

In [7]:
model.fit(x, y)

LinearRegression()

In [9]:
model = LinearRegression().fit(x, y)

In [11]:
 r_sq = model.score(x, y)
print(f"coefficient of determination: {r_sq}")

coefficient of determination: 0.715875613747954


In [13]:
 print(f"intercept: {model.intercept_}")

intercept: 5.633333333333329


In [15]:
print(f"slope: {model.coef_}")

slope: [0.54]


In [17]:
new_model = LinearRegression().fit(x, y.reshape((-1, 1)))
print(f"intercept: {new_model.intercept_}")

intercept: [5.63333333]


In [19]:
print(f"slope: {new_model.coef_}")

slope: [[0.54]]


In [21]:
 y_pred = model.predict(x)

In [25]:
y_pred = model.intercept_ + model.coef_ * x
print(f"predicted response:\n{y_pred}")

predicted response:
[[ 8.33333333]
 [13.73333333]
 [19.13333333]
 [24.53333333]
 [29.93333333]
 [35.33333333]]


In [29]:
x_new = np.arange(5).reshape((-1, 1))
x_new


array([[0],
       [1],
       [2],
       [3],
       [4]])

In [31]:
y_new = model.predict(x_new)
y_new 

array([5.63333333, 6.17333333, 6.71333333, 7.25333333, 7.79333333])

In [ ]:
#Multiple Linear Regression With scikit-learn

In [33]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [35]:
x = [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35] ]

In [37]:
y = [4, 5, 20, 14, 32, 22, 38, 43]

In [39]:
x, y = np.array(x), np.array(y)

In [41]:
x

array([[ 0,  1],
       [ 5,  1],
       [15,  2],
       [25,  5],
       [35, 11],
       [45, 15],
       [55, 34],
       [60, 35]])

In [43]:
y

array([ 4,  5, 20, 14, 32, 22, 38, 43])

In [45]:
model = LinearRegression().fit(x, y)

In [47]:
 r_sq = model.score(x, y)
print(f"coefficient of determination: {r_sq}")

coefficient of determination: 0.8615939258756775


In [49]:
print(f"intercept: {model.intercept_}")

intercept: 5.52257927519819


In [51]:
print(f"coefficients: {model.coef_}")

coefficients: [0.44706965 0.25502548]


In [53]:
y_pred = model.predict(x)
print(f"predicted response:\n{y_pred}")

predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [55]:
y_pred = model.intercept_ + np.sum(model.coef_ * x, axis=1)
print(f"predicted response:\n{y_pred}")

predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [59]:
x_new = np.arange(10).reshape((-1, 2))
x_new

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [61]:
y_new = model.predict(x_new)
y_new

array([ 5.77760476,  7.18179502,  8.58598528,  9.99017554, 11.3943658 ])

In [ ]:
#Polynomial Regression With scikit-learn

In [63]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [65]:
 x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
 y = np.array([15, 11, 2, 8, 25, 32])

In [67]:
transformer = PolynomialFeatures(degree=2, include_bias=False)


In [69]:
transformer.fit(x)

PolynomialFeatures(include_bias=False)

In [71]:
x_ = transformer.transform(x)

In [73]:
x_ = PolynomialFeatures(degree=2, include_bias=False).fit_transform(x)

In [75]:
model = LinearRegression().fit(x_, y)

In [77]:
r_sq = model.score(x_, y)
print(f"coefficient of determination: {r_sq}")

coefficient of determination: 0.8908516262498564


In [79]:
print(f"intercept: {model.intercept_}")

intercept: 21.372321428571425


In [81]:
print(f"coefficients: {model.coef_}")

coefficients: [-1.32357143  0.02839286]


In [83]:
x_ = PolynomialFeatures(degree=2, include_bias=True).fit_transform(x)

In [85]:
 x_


array([[1.000e+00, 5.000e+00, 2.500e+01],
       [1.000e+00, 1.500e+01, 2.250e+02],
       [1.000e+00, 2.500e+01, 6.250e+02],
       [1.000e+00, 3.500e+01, 1.225e+03],
       [1.000e+00, 4.500e+01, 2.025e+03],
       [1.000e+00, 5.500e+01, 3.025e+03]])

In [87]:
 model = LinearRegression(fit_intercept=False).fit(x_, y) 

In [89]:
r_sq = model.score(x_, y)
print(f"coefficient of determination: {r_sq}")

coefficient of determination: 0.8908516262498565


In [91]:
print(f"intercept: {model.intercept_}")

intercept: 0.0


In [93]:
print(f"coefficients: {model.coef_}")

coefficients: [21.37232143 -1.32357143  0.02839286]


In [95]:
y_pred = model.predict(x_)
print(f"predicted response:\n{y_pred}")

predicted response:
[15.46428571  7.90714286  6.02857143  9.82857143 19.30714286 34.46428571]


In [97]:
x = [   [0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35] ]
y = [4, 5, 20, 14, 32, 22, 38, 43]

In [99]:
x, y = np.array(x), np.array(y)

In [101]:
 x_ = PolynomialFeatures(degree=2, include_bias=False).fit_transform(x)

In [103]:
model = LinearRegression().fit(x_, y)


In [105]:
 r_sq = model.score(x_, y)
intercept, coefficients = model.intercept_, model.coef_

In [107]:
y_pred = model.predict(x_)

In [109]:
print(f"coefficient of determination: {r_sq}")

coefficient of determination: 0.9453701449127822


In [111]:
print(f"intercept: {intercept}")

intercept: 0.8430556452395734


In [113]:
print(f"coefficients:\n{coefficients}")


coefficients:
[ 2.44828275  0.16160353 -0.15259677  0.47928683 -0.4641851 ]


In [115]:
print(f"predicted response:\n{y_pred}")

predicted response:
[ 0.54047408 11.36340283 16.07809622 15.79139    29.73858619 23.50834636
 39.05631386 41.92339046]


In [117]:
#Advanced Linear Regression With statsmodels

In [119]:
import numpy as np
import statsmodels.api as sm

In [121]:
x = [   [0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35] ]
y = [4, 5, 20, 14, 32, 22, 38, 43]

In [123]:
x, y = np.array(x), np.array(y)

In [125]:
x = sm.add_constant(x)

In [127]:
model = sm.OLS(y, x)

In [129]:
results = model.fit()

In [131]:
 print(results.summary())


                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.862
Model:                            OLS   Adj. R-squared:                  0.806
Method:                 Least Squares   F-statistic:                     15.56
Date:                Tue, 25 Feb 2025   Prob (F-statistic):            0.00713
Time:                        21:51:00   Log-Likelihood:                -24.316
No. Observations:                   8   AIC:                             54.63
Df Residuals:                       5   BIC:                             54.87
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          5.5226      4.431      1.246      0.2

C:\Users\Rutuja\anaconda3\Lib\site-packages\scipy\stats\_axis_nan_policy.py:531: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  res = hypotest_fun_out(*samples, **kwds)


In [133]:
print(f"coefficient of determination: {results.rsquared}")

coefficient of determination: 0.8615939258756777


In [135]:
 print(f"adjusted coefficient of determination: {results.rsquared_adj}")

adjusted coefficient of determination: 0.8062314962259488


In [137]:
print(f"regression coefficients: {results.params}")

regression coefficients: [5.52257928 0.44706965 0.25502548]


In [141]:
print(f"predicted response:\n{results.fittedvalues}")

predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [143]:
print(f"predicted response:\n{results.predict(x)}")

predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [145]:
 x_new = sm.add_constant(np.arange(10).reshape((-1, 2)))

In [147]:
x_new

array([[1., 0., 1.],
       [1., 2., 3.],
       [1., 4., 5.],
       [1., 6., 7.],
       [1., 8., 9.]])

In [149]:
y_new = results.predict(x_new)

In [151]:
y_new

array([ 5.77760476,  7.18179502,  8.58598528,  9.99017554, 11.3943658 ])