In [ ]:
#import library's and models

In [59]:
import numpy as np

In [61]:
from sklearn.linear_model import LinearRegression  

In [63]:
from sklearn.model_selection import train_test_split


In [ ]:
#define datasets

In [65]:
x = np.array([50,55,10,20,35]).reshape(-1,1)

In [67]:
y = np.array([27,92,16,22,44])

In [ ]:
#display datasets

In [69]:
x


array([[50],
       [55],
       [10],
       [20],
       [35]])

In [71]:
y

array([27, 92, 16, 22, 44])

In [ ]:
#use linear regression model

In [73]:
model = LinearRegression()

In [75]:
model.fit(x,y)

LinearRegression()

In [77]:
model = LinearRegression().fit(x,y)

In [ ]:
#determine model score

In [79]:
rsq = model.score(x ,y)

In [122]:
print(f"model score is: {rsq}")

model score is: 0.5287075979040265


In [83]:
model.intercept_

0.5102040816326578

In [85]:
model.coef_

array([1.16734694])

In [87]:
new_model = LinearRegression().fit(x ,y.reshape(-1 ,1))

In [89]:
new_model.coef_

array([[1.16734694]])

In [91]:
y_pred = model.predict(x)

In [102]:
x_new = np.arange(5).reshape(-1, 1)

In [104]:
x_new

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [106]:
y_new = model.predict(x_new)

In [108]:
y_new

array([0.51020408, 1.67755102, 2.84489796, 4.0122449 , 5.17959184])

In [110]:
model.fit(x_new , y_new)

LinearRegression()